package hooks

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
)

// antigravityHookName is the top-level key Loom owns exclusively in
// Antigravity's hooks.json. Unlike the other three tools' single shared
// "hooks" key (dedup-and-append per entry), Antigravity's schema is
// keyed by arbitrary hook-group names the author picks — nobody else
// would coincidentally choose this exact name, so Loom can deterministically
// recompute and overwrite its own key's whole value on every install
// rather than diffing entries within it.
const antigravityHookName = "loom-reminder"

// antigravityScriptContent builds a PreToolUse script emitting
// Antigravity's decision/reason contract.
//
// UNVERIFIED, DO NOT REMOVE THIS COMMENT UNTIL CONFIRMED LIVE: Antigravity's
// documented PreToolUse output is {"decision": "allow"|"deny"|..., "reason":
// "..."}. Loom emits decision:"allow" + reason:<message>, but the docs only
// clearly confirm "reason" is surfaced to the agent on deny/ask, not allow.
// If unconfirmed, this hook is gracefully inert — it installs cleanly and
// never errors, but the reminder may simply never reach the agent. Do not
// treat Antigravity support as shipped until this is checked live.
func antigravityScriptContent(message, installCmd string) string {
	payload, _ := json.Marshal(map[string]any{
		"decision": "allow",
		"reason":   message,
	})

	return fmt.Sprintf("#!/bin/bash\n# Generated by `%s` — do not edit by hand, re-run instead.\necho %s\n", installCmd, shellQuote(string(payload)))
}

// mergeAntigravityHooksFile ensures antigravityHookName maps to a freshly
// computed map[string][]hookMatcher built from wirings, preserving every
// other top-level key (other tools' own named hook groups) untouched.
// Unlike mergeSettingsFile/mergeCursorHooksFile, there's no per-entry
// dedup — Loom owns this whole key and recomputes it in full each time.
// Change detection compares the parsed existing value against the freshly
// built one rather than raw bytes, since a pretty-printed file on disk
// will never byte-match a freshly (compact) marshaled value even when
// semantically identical.
func mergeAntigravityHooksFile(path string, wirings []hookWiring) (bool, error) {
	raw := map[string]json.RawMessage{}
	data, err := os.ReadFile(path)
	switch {
	case err == nil:
		if err := json.Unmarshal(data, &raw); err != nil {
			return false, fmt.Errorf("parsing %s: %w", path, err)
		}
	case os.IsNotExist(err):
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return false, fmt.Errorf("creating hooks config dir: %w", err)
		}
	default:
		return false, fmt.Errorf("reading %s: %w", path, err)
	}

	hooksByEvent := map[string][]hookMatcher{}
	for _, w := range wirings {
		hooksByEvent[w.event] = append(hooksByEvent[w.event], hookMatcher{
			Matcher: w.matcher,
			Hooks:   []hookEntry{{Type: "command", Command: w.command}},
		})
	}

	if existing, ok := raw[antigravityHookName]; ok {
		var existingHooks map[string][]hookMatcher
		if err := json.Unmarshal(existing, &existingHooks); err == nil && reflect.DeepEqual(existingHooks, hooksByEvent) {
			return false, nil
		}
	}

	newValue, err := json.Marshal(hooksByEvent)
	if err != nil {
		return false, fmt.Errorf("encoding %s: %w", antigravityHookName, err)
	}
	raw[antigravityHookName] = newValue

	out, err := json.MarshalIndent(raw, "", "  ")
	if err != nil {
		return false, fmt.Errorf("encoding %s: %w", path, err)
	}

	if err := os.WriteFile(path, out, 0o644); err != nil {
		return false, fmt.Errorf("writing %s: %w", path, err)
	}

	return true, nil
}

// InstallAntigravity writes Loom's reminder script into
// <root>/.agents/hooks/ and wires it into a dedicated
// <root>/.agents/hooks.json under the antigravityHookName key's
// PreToolUse event. Unlike Install/InstallCodex/InstallCursor, there is
// deliberately no InstallAntigravityGlobal: Antigravity has no
// SessionStart-equivalent event (only PreToolUse, PostToolUse,
// PreInvocation, PostInvocation, Stop), so there's no honest way to build
// the lightweight one-time global nudge the other three tools have.
//
// Antigravity has no unified "edit" tool the way Codex (apply_patch) or
// Cursor (Write) do — file mutation splits across three tool names, all
// matched here.
//
// Antigravity's docs don't state a cwd guarantee for project-scoped hook
// commands the way Cursor's do, or recommend a git-toplevel convention
// the way Codex's do — an absolute path sidesteps that unverified
// behavior entirely rather than guessing.
func InstallAntigravity(root string) (bool, error) {
	hooksDir := filepath.Join(root, ".agents", "hooks")
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return false, fmt.Errorf("creating hooks dir: %w", err)
	}

	scriptPath := filepath.Join(hooksDir, preToolUseScript)
	scriptsChanged, err := writeScriptIfChanged(scriptPath, antigravityScriptContent(preToolUseMessage, "loom hooks install-antigravity"))
	if err != nil {
		return false, err
	}

	settingsChanged, err := mergeAntigravityHooksFile(filepath.Join(root, ".agents", "hooks.json"), []hookWiring{
		{event: "PreToolUse", matcher: "write_to_file|replace_file_content|multi_replace_file_content", command: scriptPath},
	})
	if err != nil {
		return false, err
	}

	return scriptsChanged || settingsChanged, nil
}
