package hooks

import (
	"encoding/json"
	"fmt"
	"maps"
	"os"
	"path/filepath"
)

// cursorPostToolUseScript is deliberately its own name, not preToolUseScript
// reused: Cursor's per-edit reminder fires on postToolUse (see InstallCursor),
// so a script named "pretooluse" on disk would misdescribe when it runs.
const cursorPostToolUseScript = "loom-remind-posttooluse.sh"

// cursorHookHandler is one entry in Cursor's flat per-event array:
// {"command": "...", "matcher": "...", "timeout": ..., ...}. Unlike
// hookEntry/hookMatcher's two-level Claude/Codex shape, there's no nested
// "hooks" sub-array — command, matcher, timeout, loop_limit, and
// failClosed all live on the same object, one level flatter. Preserves
// any field Loom doesn't itself set (timeout, loop_limit, failClosed,
// type, ...), same reasoning as hookEntry.
type cursorHookHandler struct {
	Command string
	Matcher string
	extra   map[string]json.RawMessage
}

func (h cursorHookHandler) MarshalJSON() ([]byte, error) {
	m := make(map[string]json.RawMessage, len(h.extra)+2)
	maps.Copy(m, h.extra)

	commandJSON, err := json.Marshal(h.Command)
	if err != nil {
		return nil, err
	}
	m["command"] = commandJSON

	if h.Matcher != "" {
		matcherJSON, err := json.Marshal(h.Matcher)
		if err != nil {
			return nil, err
		}
		m["matcher"] = matcherJSON
	}

	return json.Marshal(m)
}

func (h *cursorHookHandler) UnmarshalJSON(data []byte) error {
	m := map[string]json.RawMessage{}
	if err := json.Unmarshal(data, &m); err != nil {
		return err
	}

	if raw, ok := m["command"]; ok {
		if err := json.Unmarshal(raw, &h.Command); err != nil {
			return fmt.Errorf("parsing hook command: %w", err)
		}
		delete(m, "command")
	}
	if raw, ok := m["matcher"]; ok {
		if err := json.Unmarshal(raw, &h.Matcher); err != nil {
			return fmt.Errorf("parsing hook matcher: %w", err)
		}
		delete(m, "matcher")
	}

	if len(m) > 0 {
		h.extra = m
	}

	return nil
}

// cursorScriptContent builds a Cursor hook script. Both events Loom uses
// (sessionStart, postToolUse) accept the same flat {"additional_context":
// "..."} shape — no hookSpecificOutput wrapper, snake_case field, no
// per-event branching needed. Doesn't cover Cursor's other output fields
// (env, permission, user_message, updated_input) — Loom never sets them.
func cursorScriptContent(message, installCmd string) string {
	payload, _ := json.Marshal(map[string]any{
		"additional_context": message,
	})

	return fmt.Sprintf("#!/bin/bash\n# Generated by `%s` — do not edit by hand, re-run instead.\necho %s\n", installCmd, shellQuote(string(payload)))
}

// cursorGlobalScriptContent is cursorScriptContent's global counterpart,
// unconditional the same way globalScriptContent is for Claude/Codex's
// global hook: Loom resolves an ad-hoc project even outside git, so the
// reminder fires on every session rather than gating on git.
func cursorGlobalScriptContent(message, installCmd string) string {
	payload, _ := json.Marshal(map[string]any{
		"additional_context": message,
	})

	return fmt.Sprintf("#!/bin/bash\n# Generated by `%s` — do not edit by hand, re-run instead.\necho %s\n", installCmd, shellQuote(string(payload)))
}

// mergeCursorHooksFile ensures each of wirings exists in cursorPath's flat
// "hooks" block (map[string][]cursorHookHandler), preserving every other
// top-level key and every handler Loom didn't add. Sets "version": 1 only
// when creating the file fresh — never touches an existing version value,
// present or absent.
func mergeCursorHooksFile(cursorPath string, wirings []hookWiring) (bool, error) {
	raw := map[string]json.RawMessage{}
	isNew := false

	data, err := os.ReadFile(cursorPath)
	switch {
	case err == nil:
		if err := json.Unmarshal(data, &raw); err != nil {
			return false, fmt.Errorf("parsing %s: %w", cursorPath, err)
		}
	case os.IsNotExist(err):
		isNew = true
		if err := os.MkdirAll(filepath.Dir(cursorPath), 0o755); err != nil {
			return false, fmt.Errorf("creating hooks config dir: %w", err)
		}
	default:
		return false, fmt.Errorf("reading %s: %w", cursorPath, err)
	}

	hooksByEvent := map[string][]cursorHookHandler{}
	if existing, ok := raw["hooks"]; ok {
		if err := json.Unmarshal(existing, &hooksByEvent); err != nil {
			return false, fmt.Errorf("parsing hooks in %s: %w", cursorPath, err)
		}
	}

	changed := false
	for _, w := range wirings {
		changed = addCursorHookIfMissing(hooksByEvent, w.event, w.matcher, w.command) || changed
	}

	if isNew {
		raw["version"] = json.RawMessage("1")
		changed = true
	}

	if !changed {
		return false, nil
	}

	hooksJSON, err := json.Marshal(hooksByEvent)
	if err != nil {
		return false, fmt.Errorf("encoding hooks: %w", err)
	}
	raw["hooks"] = hooksJSON

	out, err := json.MarshalIndent(raw, "", "  ")
	if err != nil {
		return false, fmt.Errorf("encoding %s: %w", cursorPath, err)
	}

	if err := os.WriteFile(cursorPath, out, 0o644); err != nil {
		return false, fmt.Errorf("writing %s: %w", cursorPath, err)
	}

	return true, nil
}

// addCursorHookIfMissing is addHookIfMissing's flat-shape counterpart:
// dedups by exact Command match within an event, appends a new handler
// (not a new matcher-group — Cursor has no matcher-group level) if not
// found.
func addCursorHookIfMissing(hooksByEvent map[string][]cursorHookHandler, event, matcher, command string) bool {
	for _, h := range hooksByEvent[event] {
		if h.Command == command {
			return false
		}
	}

	hooksByEvent[event] = append(hooksByEvent[event], cursorHookHandler{
		Matcher: matcher,
		Command: command,
	})

	return true
}

// InstallCursor writes Loom's reminder scripts into <root>/.cursor/hooks/
// and wires them into a dedicated <root>/.cursor/hooks.json under
// sessionStart (no matcher) and postToolUse (matcher "Write"). Cursor's
// preToolUse output has no context-injection field — only postToolUse
// supports additional_context — so this reminder fires just after an
// edit instead of just before it, a deliberate consequence of Cursor's
// contract, not an oversight.
//
// Cursor guarantees project-scoped hook commands run with cwd = project
// root always, so — unlike Claude's ${CLAUDE_PROJECT_DIR} or Codex's
// $(git rev-parse --show-toplevel) — a plain relative path is portable
// here with no extra trick needed.
func InstallCursor(root string) (bool, error) {
	hooksDir := filepath.Join(root, ".cursor", "hooks")
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return false, fmt.Errorf("creating hooks dir: %w", err)
	}

	scriptsChanged := false
	for _, s := range []struct {
		name, message string
	}{
		{sessionStartScript, sessionStartMessage},
		{cursorPostToolUseScript, preToolUseMessage},
	} {
		changed, err := writeScriptIfChanged(filepath.Join(hooksDir, s.name), cursorScriptContent(s.message, "loom hooks install-cursor"))
		if err != nil {
			return false, err
		}
		scriptsChanged = scriptsChanged || changed
	}

	settingsChanged, err := mergeCursorHooksFile(filepath.Join(root, ".cursor", "hooks.json"), []hookWiring{
		{event: "sessionStart", command: ".cursor/hooks/" + sessionStartScript},
		{event: "postToolUse", matcher: "Write", command: ".cursor/hooks/" + cursorPostToolUseScript},
	})
	if err != nil {
		return false, err
	}

	return scriptsChanged || settingsChanged, nil
}

// InstallCursorGlobal writes a single reminder script into
// ~/.cursor/hooks/ and wires it into the user's own ~/.cursor/hooks.json
// under sessionStart, not any project's. Mirrors InstallGlobal.
func InstallCursorGlobal() (bool, error) {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return false, fmt.Errorf("resolving home directory: %w", err)
	}

	hooksDir := filepath.Join(homeDir, ".cursor", "hooks")
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return false, fmt.Errorf("creating hooks dir: %w", err)
	}

	scriptPath := filepath.Join(hooksDir, globalRemindScript)
	scriptsChanged, err := writeScriptIfChanged(scriptPath, cursorGlobalScriptContent(globalRemindMessage, "loom hooks install-cursor-global"))
	if err != nil {
		return false, err
	}

	settingsChanged, err := mergeCursorHooksFile(filepath.Join(homeDir, ".cursor", "hooks.json"), []hookWiring{
		{event: "sessionStart", command: scriptPath},
	})
	if err != nil {
		return false, err
	}

	return scriptsChanged || settingsChanged, nil
}
