// Package hooks generates Claude Code hooks that remind an agent that Loom
// exists, without relying on the agent remembering it was told once.
// Everything here is inert text: the hooks never call `loom` themselves,
// they only inject a static reminder into the agent's context. The agent
// still does all the actual work by calling Loom's MCP tools.
//
// Install sets up project-scoped hooks (in <root>/.claude/) for a repo
// that already uses Loom — SessionStart once per session, PreToolUse on
// every Write/Edit/MultiEdit so the reminder survives context drift.
// InstallGlobal sets up a single, much lighter SessionStart hook in the
// user's own ~/.claude/settings.json — a one-time "Loom exists, consider
// it" nudge for any git repo, whether or not that project has adopted
// Loom yet.
package hooks

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	sessionStartScript = "loom-remind-sessionstart.sh"
	preToolUseScript   = "loom-remind-pretooluse.sh"
	globalRemindScript = "loom-global-remind.sh"

	sessionStartMessage = "This project uses Loom for shared agent coordination. Use the Loom MCP tools (loom_status, loom_claim, loom_release, loom_log) to see current activity and record your own work as you go. Agents use the MCP tools; the CLI is for humans."
	preToolUseMessage   = "This project uses Loom for shared agent coordination. Before editing this file, use the Loom MCP tools (loom_status, loom_claim) to check for and record active work on it. Use the MCP tools, not the CLI."
	globalRemindMessage = "This directory is a git repository. Loom is a local, no-account coordination tool for coding agents: a shared event log and claim system so agents do not silently overwrite work another agent already has in progress. If this project already has Loom set up, use the loom_status, loom_claim, loom_release, and loom_log MCP tools. If it does not yet, you can set it up here by calling loom_hooks_install."
)

func scriptContent(eventName, message string) string {
	payload, _ := json.Marshal(map[string]any{
		"hookSpecificOutput": map[string]any{
			"hookEventName":     eventName,
			"additionalContext": message,
		},
	})

	return fmt.Sprintf("#!/bin/bash\n# Generated by `loom hooks install` — do not edit by hand, re-run instead.\necho %s\n", shellQuote(string(payload)))
}

// globalScriptContent is scriptContent's global counterpart: unlike the
// project-scoped scripts, which only ever get installed into a repo that
// already wants Loom, this one runs on every Claude Code session
// everywhere. It only fires the reminder when the session is actually
// inside a git repo, so it stays silent for sessions that are never
// going to touch a project Loom could help with.
func globalScriptContent(eventName, message string) string {
	payload, _ := json.Marshal(map[string]any{
		"hookSpecificOutput": map[string]any{
			"hookEventName":     eventName,
			"additionalContext": message,
		},
	})

	return fmt.Sprintf(
		"#!/bin/bash\n# Generated by `loom hooks install-global` — do not edit by hand, re-run instead.\nif git rev-parse --is-inside-work-tree >/dev/null 2>&1; then\n  echo %s\nfi\n",
		shellQuote(string(payload)),
	)
}

// shellQuote wraps s in single quotes for safe use inside a generated
// shell script. The messages above are hand-written without apostrophes,
// so this never has to deal with escaping a quote inside s — it's here
// as a guard against a future message accidentally introducing one.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

type hookEntry struct {
	Type    string `json:"type"`
	Command string `json:"command"`
}

type hookMatcher struct {
	Matcher string      `json:"matcher,omitempty"`
	Hooks   []hookEntry `json:"hooks"`
}

// Install writes Loom's reminder scripts into <root>/.claude/hooks/ and
// wires them into <root>/.claude/settings.json under the SessionStart and
// PreToolUse events, merging into whatever's already there rather than
// overwriting it. It's safe to call repeatedly: unchanged scripts aren't
// rewritten, and an event already wired to Loom's command isn't duplicated.
// Returns whether anything on disk actually changed.
func Install(root string) (bool, error) {
	hooksDir := filepath.Join(root, ".claude", "hooks")
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return false, fmt.Errorf("creating hooks dir: %w", err)
	}

	scriptsChanged := false
	for _, s := range []struct {
		name, eventName, message string
	}{
		{sessionStartScript, "SessionStart", sessionStartMessage},
		{preToolUseScript, "PreToolUse", preToolUseMessage},
	} {
		changed, err := writeScriptIfChanged(filepath.Join(hooksDir, s.name), scriptContent(s.eventName, s.message))
		if err != nil {
			return false, err
		}
		scriptsChanged = scriptsChanged || changed
	}

	settingsChanged, err := mergeSettingsFile(filepath.Join(root, ".claude", "settings.json"), []hookWiring{
		{event: "SessionStart", command: "${CLAUDE_PROJECT_DIR}/.claude/hooks/" + sessionStartScript},
		{event: "PreToolUse", matcher: "Write|Edit|MultiEdit", command: "${CLAUDE_PROJECT_DIR}/.claude/hooks/" + preToolUseScript},
	})
	if err != nil {
		return false, err
	}

	return scriptsChanged || settingsChanged, nil
}

// InstallGlobal writes a single reminder script into ~/.claude/hooks/ and
// wires it into the user's own ~/.claude/settings.json under SessionStart
// — not any project's settings.json. Unlike Install, this only needs to
// run once per machine: from then on, every Claude Code session in every
// git repo gets a one-time nudge that Loom exists, whether or not that
// particular project has adopted it yet. Same idempotency guarantees as
// Install.
func InstallGlobal() (bool, error) {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return false, fmt.Errorf("resolving home directory: %w", err)
	}

	hooksDir := filepath.Join(homeDir, ".claude", "hooks")
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return false, fmt.Errorf("creating hooks dir: %w", err)
	}

	scriptPath := filepath.Join(hooksDir, globalRemindScript)
	scriptsChanged, err := writeScriptIfChanged(scriptPath, globalScriptContent("SessionStart", globalRemindMessage))
	if err != nil {
		return false, err
	}

	settingsChanged, err := mergeSettingsFile(filepath.Join(homeDir, ".claude", "settings.json"), []hookWiring{
		{event: "SessionStart", command: scriptPath},
	})
	if err != nil {
		return false, err
	}

	return scriptsChanged || settingsChanged, nil
}

func writeScriptIfChanged(path, content string) (bool, error) {
	existing, err := os.ReadFile(path)
	if err == nil && string(existing) == content {
		return false, nil
	}
	if err != nil && !os.IsNotExist(err) {
		return false, fmt.Errorf("reading %s: %w", path, err)
	}

	if err := os.WriteFile(path, []byte(content), 0o755); err != nil {
		return false, fmt.Errorf("writing %s: %w", path, err)
	}

	return true, nil
}

// hookWiring is one (event, matcher, command) entry to ensure exists in a
// settings.json's hooks block. matcher is left empty for events like
// SessionStart that don't match against a tool name.
type hookWiring struct {
	event   string
	matcher string
	command string
}

func mergeSettingsFile(settingsPath string, wirings []hookWiring) (bool, error) {
	raw := map[string]json.RawMessage{}
	data, err := os.ReadFile(settingsPath)
	switch {
	case err == nil:
		if err := json.Unmarshal(data, &raw); err != nil {
			return false, fmt.Errorf("parsing %s: %w", settingsPath, err)
		}
	case os.IsNotExist(err):
		if err := os.MkdirAll(filepath.Dir(settingsPath), 0o755); err != nil {
			return false, fmt.Errorf("creating .claude dir: %w", err)
		}
	default:
		return false, fmt.Errorf("reading %s: %w", settingsPath, err)
	}

	hooksByEvent := map[string][]hookMatcher{}
	if existing, ok := raw["hooks"]; ok {
		if err := json.Unmarshal(existing, &hooksByEvent); err != nil {
			return false, fmt.Errorf("parsing hooks in %s: %w", settingsPath, err)
		}
	}

	changed := false
	for _, w := range wirings {
		changed = addHookIfMissing(hooksByEvent, w.event, w.matcher, w.command) || changed
	}

	if !changed {
		return false, nil
	}

	hooksJSON, err := json.Marshal(hooksByEvent)
	if err != nil {
		return false, fmt.Errorf("encoding hooks: %w", err)
	}
	raw["hooks"] = hooksJSON

	out, err := json.MarshalIndent(raw, "", "  ")
	if err != nil {
		return false, fmt.Errorf("encoding %s: %w", settingsPath, err)
	}

	if err := os.WriteFile(settingsPath, out, 0o644); err != nil {
		return false, fmt.Errorf("writing %s: %w", settingsPath, err)
	}

	return true, nil
}

// addHookIfMissing appends a new matcher group running command under
// event, unless some existing group under that event already runs it —
// which is what makes Install idempotent.
func addHookIfMissing(hooksByEvent map[string][]hookMatcher, event, matcher, command string) bool {
	for _, group := range hooksByEvent[event] {
		for _, h := range group.Hooks {
			if h.Command == command {
				return false
			}
		}
	}

	hooksByEvent[event] = append(hooksByEvent[event], hookMatcher{
		Matcher: matcher,
		Hooks:   []hookEntry{{Type: "command", Command: command}},
	})

	return true
}
