// Package hooks generates project-scoped Claude Code hooks that remind an
// agent working in this repo that Loom exists, without relying on the
// agent remembering it was told once. Everything here is inert text: the
// hooks never call `loom` themselves, they only inject a static reminder
// into the agent's context — SessionStart once per session, PreToolUse on
// every Write/Edit/MultiEdit so the reminder survives context drift. The
// agent still does all the actual work by calling Loom's MCP tools.
package hooks

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	sessionStartScript = "loom-remind-sessionstart.sh"
	preToolUseScript   = "loom-remind-pretooluse.sh"

	sessionStartMessage = "This project uses Loom for shared agent coordination. Use the Loom MCP tools (loom_status, loom_claim, loom_release, loom_log) to see current activity and record your own work as you go. Agents use the MCP tools; the CLI is for humans."
	preToolUseMessage   = "This project uses Loom for shared agent coordination. Before editing this file, use the Loom MCP tools (loom_status, loom_claim) to check for and record active work on it. Use the MCP tools, not the CLI."
)

func scriptContent(eventName, message string) string {
	payload, _ := json.Marshal(map[string]any{
		"hookSpecificOutput": map[string]any{
			"hookEventName":     eventName,
			"additionalContext": message,
		},
	})

	return fmt.Sprintf("#!/bin/bash\n# Generated by `loom hooks install` — do not edit by hand, re-run instead.\necho %s\n", shellQuote(string(payload)))
}

// shellQuote wraps s in single quotes for safe use inside a generated
// shell script. The messages above are hand-written without apostrophes,
// so this never has to deal with escaping a quote inside s — it's here
// as a guard against a future message accidentally introducing one.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

type hookEntry struct {
	Type    string `json:"type"`
	Command string `json:"command"`
}

type hookMatcher struct {
	Matcher string      `json:"matcher,omitempty"`
	Hooks   []hookEntry `json:"hooks"`
}

// Install writes Loom's reminder scripts into <root>/.claude/hooks/ and
// wires them into <root>/.claude/settings.json under the SessionStart and
// PreToolUse events, merging into whatever's already there rather than
// overwriting it. It's safe to call repeatedly: unchanged scripts aren't
// rewritten, and an event already wired to Loom's command isn't duplicated.
// Returns whether anything on disk actually changed.
func Install(root string) (bool, error) {
	hooksDir := filepath.Join(root, ".claude", "hooks")
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return false, fmt.Errorf("creating hooks dir: %w", err)
	}

	scriptsChanged := false
	for _, s := range []struct {
		name, eventName, message string
	}{
		{sessionStartScript, "SessionStart", sessionStartMessage},
		{preToolUseScript, "PreToolUse", preToolUseMessage},
	} {
		changed, err := writeScriptIfChanged(filepath.Join(hooksDir, s.name), scriptContent(s.eventName, s.message))
		if err != nil {
			return false, err
		}
		scriptsChanged = scriptsChanged || changed
	}

	settingsChanged, err := mergeSettings(root)
	if err != nil {
		return false, err
	}

	return scriptsChanged || settingsChanged, nil
}

func writeScriptIfChanged(path, content string) (bool, error) {
	existing, err := os.ReadFile(path)
	if err == nil && string(existing) == content {
		return false, nil
	}
	if err != nil && !os.IsNotExist(err) {
		return false, fmt.Errorf("reading %s: %w", path, err)
	}

	if err := os.WriteFile(path, []byte(content), 0o755); err != nil {
		return false, fmt.Errorf("writing %s: %w", path, err)
	}

	return true, nil
}

func mergeSettings(root string) (bool, error) {
	settingsPath := filepath.Join(root, ".claude", "settings.json")

	raw := map[string]json.RawMessage{}
	data, err := os.ReadFile(settingsPath)
	switch {
	case err == nil:
		if err := json.Unmarshal(data, &raw); err != nil {
			return false, fmt.Errorf("parsing %s: %w", settingsPath, err)
		}
	case os.IsNotExist(err):
		if err := os.MkdirAll(filepath.Dir(settingsPath), 0o755); err != nil {
			return false, fmt.Errorf("creating .claude dir: %w", err)
		}
	default:
		return false, fmt.Errorf("reading %s: %w", settingsPath, err)
	}

	hooksByEvent := map[string][]hookMatcher{}
	if existing, ok := raw["hooks"]; ok {
		if err := json.Unmarshal(existing, &hooksByEvent); err != nil {
			return false, fmt.Errorf("parsing hooks in %s: %w", settingsPath, err)
		}
	}

	changed := false
	changed = addHookIfMissing(hooksByEvent, "SessionStart", "", "${CLAUDE_PROJECT_DIR}/.claude/hooks/"+sessionStartScript) || changed
	changed = addHookIfMissing(hooksByEvent, "PreToolUse", "Write|Edit|MultiEdit", "${CLAUDE_PROJECT_DIR}/.claude/hooks/"+preToolUseScript) || changed

	if !changed {
		return false, nil
	}

	hooksJSON, err := json.Marshal(hooksByEvent)
	if err != nil {
		return false, fmt.Errorf("encoding hooks: %w", err)
	}
	raw["hooks"] = hooksJSON

	out, err := json.MarshalIndent(raw, "", "  ")
	if err != nil {
		return false, fmt.Errorf("encoding %s: %w", settingsPath, err)
	}

	if err := os.WriteFile(settingsPath, out, 0o644); err != nil {
		return false, fmt.Errorf("writing %s: %w", settingsPath, err)
	}

	return true, nil
}

// addHookIfMissing appends a new matcher group running command under
// event, unless some existing group under that event already runs it —
// which is what makes Install idempotent.
func addHookIfMissing(hooksByEvent map[string][]hookMatcher, event, matcher, command string) bool {
	for _, group := range hooksByEvent[event] {
		for _, h := range group.Hooks {
			if h.Command == command {
				return false
			}
		}
	}

	hooksByEvent[event] = append(hooksByEvent[event], hookMatcher{
		Matcher: matcher,
		Hooks:   []hookEntry{{Type: "command", Command: command}},
	})

	return true
}
