package hooks

import (
	"encoding/json"
	"fmt"
	"strings"
)

const (
	sessionStartScript = "loom-global-remind.sh"
	promptSubmitScript = "loom-remind-userpromptsubmit.sh"

	sessionStartMessage = "Loom is available globally for coordination between coding agents. Prefer its MCP tools over the CLI. At the start of work, call loom_global_all for cross-project context. Before editing, claim the relevant path with loom_claim; release it when done; and record meaningful decisions with loom_log. Project-scoped tools require your actual current working directory as cwd."
	promptSubmitMessage = "Remember to use Loom's MCP tools for shared agent coordination: check loom_global_all when context may have changed, claim paths before editing, release them when done, and log meaningful decisions. Always pass your actual current working directory as cwd to project-scoped tools."
)

func nestedScriptContent(eventName, message string, harness Harness) string {
	payload, _ := json.Marshal(map[string]any{
		"hookSpecificOutput": map[string]any{
			"hookEventName":     eventName,
			"additionalContext": message,
		},
	})
	return generatedScript(string(payload), harness)
}

func cursorScriptContent(message string) string {
	payload, _ := json.Marshal(map[string]any{"additional_context": message})
	return generatedScript(string(payload), HarnessCursor)
}

func generatedScript(payload string, harness Harness) string {
	return fmt.Sprintf(
		"#!/bin/bash\n# Generated by `loom hooks install %s` — do not edit by hand; re-run the command instead.\necho %s\n",
		harness,
		shellQuote(payload),
	)
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", `'\''`) + "'"
}
