package hooks

import (
	"encoding/json"
	"fmt"
	"strings"
)

const (
	sessionStartScript  = "loom-global-remind.sh"
	promptSubmitScript  = "loom-remind-userpromptsubmit.sh"
	subagentStartScript = "loom-remind-subagentstart.sh"
	cursorTaskScript    = "loom-remind-subagent-task.sh"

	sessionStartMessage   = "Loom is available globally for coordination between coding agents. Prefer its MCP tools over the CLI. At the start of work, call loom_global_all for cross-project context. Before editing, claim the relevant path with loom_claim; release it when done; and record meaningful decisions with loom_log. Project-scoped tools require your actual current working directory as cwd."
	promptSubmitMessage   = "Remember to use Loom's MCP tools for shared agent coordination: check loom_global_all when context may have changed, claim paths before editing, release them when done, and log meaningful decisions. Always pass your actual current working directory as cwd to project-scoped tools."
	subagentStartMessage  = "This subagent must participate in Loom coordination. Before starting work, call loom_global_all. Use Loom's MCP tools and pass your actual current working directory as cwd to project-scoped tools. Before editing a path, call loom_claim and proceed only when it reports that you claimed the path; treat an already-claimed response as a sibling conflict. Release only claims you personally created, release them when done, and record meaningful decisions with loom_log. If Loom's MCP tools are unavailable, report that and do not edit files."
	subagentContextMarker = "<loom-subagent-context>"
)

func nestedScriptContent(eventName, message string, harness Harness) string {
	payload, _ := json.Marshal(map[string]any{
		"hookSpecificOutput": map[string]any{
			"hookEventName":     eventName,
			"additionalContext": message,
		},
	})
	return generatedScript(string(payload), harness)
}

func cursorScriptContent(message string) string {
	payload, _ := json.Marshal(map[string]any{"additional_context": message})
	return generatedScript(string(payload), HarnessCursor)
}

func cursorSubagentScriptContent(executable string) string {
	return fmt.Sprintf(
		"#!/bin/bash\n# Generated by `loom hooks install cursor` — do not edit by hand; re-run the command instead.\nloom_bin=%s\nif [ ! -x \"$loom_bin\" ]; then\n  loom_bin=$(command -v loom 2>/dev/null || true)\nfi\nif [ -z \"$loom_bin\" ]; then\n  echo '{\"permission\":\"allow\"}'\n  exit 0\nfi\nexec \"$loom_bin\" hooks _cursor-subagent-context\n",
		shellQuote(executable),
	)
}

func generatedScript(payload string, harness Harness) string {
	return fmt.Sprintf(
		"#!/bin/bash\n# Generated by `loom hooks install %s` — do not edit by hand; re-run the command instead.\necho %s\n",
		harness,
		shellQuote(payload),
	)
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", `'\''`) + "'"
}
