#!/bin/bash
# Generated by `loom hooks install` — do not edit by hand, re-run instead.
echo '{"hookSpecificOutput":{"additionalContext":"This project uses Loom for shared agent coordination. Before editing this file, use the Loom MCP tools (loom_status, loom_claim) to check for and record active work on it. Use the MCP tools, not the CLI.","hookEventName":"PreToolUse"}}'
