#!/bin/bash
# Generated by `loom hooks install-codex` — do not edit by hand, re-run instead.
echo '{"hookSpecificOutput":{"additionalContext":"This project uses Loom for shared agent coordination. Use the Loom MCP tools (loom_status, loom_claim, loom_release, loom_log) to see current activity and record your own work as you go. Agents use the MCP tools; the CLI is for humans.","hookEventName":"SessionStart"}}'
